// Mocks generated by Mockito 5.4.6 from annotations
// in card_advisor/test/recommendation_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:card_advisor/database/app_database.dart' as _i2;
import 'package:card_advisor/database/daos/cards_dao.dart' as _i3;
import 'package:card_advisor/database/daos/merchants_dao.dart' as _i6;
import 'package:card_advisor/database/daos/spend_dao.dart' as _i7;
import 'package:card_advisor/database/daos/user_wallet_dao.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CardsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardsDao extends _i1.Mock implements _i3.CardsDao {
  MockCardsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllCards() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCards, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getCardById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCardById, [id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> insertCard(Map<String, dynamic>? card) =>
      (super.noSuchMethod(
            Invocation.method(#insertCard, [card]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertCardRewards(
    String? cardId,
    List<Map<String, dynamic>>? rewards,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCardRewards, [cardId, rewards]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getRewardsForCard(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#getRewardsForCard, [cardId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [UserWalletDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserWalletDao extends _i1.Mock implements _i5.UserWalletDao {
  MockUserWalletDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<void> addToWallet(String? cardId, String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#addToWallet, [cardId, nickname]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromWallet(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWallet, [cardId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUserCards() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCards, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> isCardInWallet(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#isCardInWallet, [cardId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [MerchantsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMerchantsDao extends _i1.Mock implements _i6.MerchantsDao {
  MockMerchantsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<Map<String, dynamic>?> getMerchantById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMerchantById, [id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> insertMerchant(Map<String, dynamic>? merchant) =>
      (super.noSuchMethod(
            Invocation.method(#insertMerchant, [merchant]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllMerchants() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMerchants, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [SpendDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpendDao extends _i1.Mock implements _i7.SpendDao {
  MockSpendDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<void> logSpend({
    required String? merchantId,
    required int? amountCents,
    String? category,
    DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSpend, [], {
              #merchantId: merchantId,
              #amountCents: amountCents,
              #category: category,
              #timestamp: timestamp,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSpendForMerchant(
    String? merchantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpendForMerchant, [merchantId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSpendForCategory(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpendForCategory, [category]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> getMerchantVisitCount(String? merchantId) =>
      (super.noSuchMethod(
            Invocation.method(#getMerchantVisitCount, [merchantId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
