name: card_advisor
description: "PerkMax - Maximize your credit card rewards."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  flutter_secure_storage: ^9.0.0
  geocoding: ^4.0.0
  geolocator: ^13.0.1
  google_fonts: ^8.0.0
  google_generative_ai: ^0.4.7
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  uuid: ^4.5.2
  window_manager: ^0.5.1
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.3
  build_runner: ^2.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/cards_seed.json
